name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Install Pulumi CLI
        uses: pulumi/actions@v5
        - uses: pulumi/actions@v6
        with:
          command: preview
          stack-name: escbarros-org/infra-flora/dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Login to Pulumi
        run: pulumi login
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Select Pulumi Stack
        run: pulumi stack select dev

      - name: Install Dependencies
        run: npm install

      - name: Destroy Pulumi Stack
        run: pulumi destroy --yes
