name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/flora-api:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/flora-api:${{ github.sha }}

  deploy:
    name: Deploy to Cloud
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install project dependencies
        working-directory: infra
        run: npm install

      - name: Install Pulumi CLI
        uses: pulumi/actions@v6

      - name: Configure Pulumi
        working-directory: infra
        run: |
          pulumi login
          pulumi stack select escbarros-org/infra-flora/dev
          pulumi config set dockerUsername ${{ secrets.DOCKERHUB_USERNAME }}
          pulumi config set --secret dockerPassword ${{ secrets.DOCKERHUB_TOKEN }}
          pulumi config set --secret envFile "${{ secrets.ENV_FILE }}"
          pulumi config set aws:region sa-east-1
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}

      - name: Deploy with Pulumi
        working-directory: infra
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: pulumi up --yes
